export class Stock {
    productId: string;
    productName: string;
    productCode: string;
    categoryID: string;
    subCategoryId: string;
    supId: string;
    uomId: string;
    uOMName:string;
    sBarCode: string;
    pBarCode: string;
    itemDescription: string;
    productDescription: string;
    expireDate: Date;
    isExpireActive: string;
    maxOrder: string;
    minOrder: string;
    reOrderlevel: string;
    cpu: number;
    rPU: number;
    qty:number;
    categoryName:string;
    subcategoryName:string;
  supplyName: string;
  pStock: string;
  pRQty: string;
  ppeningStock: string;
  indQty: string;
  inpvQty: string;
  pOapvQty: string;
  pOQCQty: string;
  pOQty: string;
  rptType:string;
}