export class Product {
    productId: string;
    productName: string;
    productCode: string;
    categoryID: string;
    subCategoryId: string;
    uomId: string;
    uOMName:string;
    sBarCode: string;
    pBarCode: string;
    itemDescription: string;
    productDescription: string;
    expireDate: Date;
    sexpireDate: Date;
    eexpireDate: Date;
    isExpireActive: string;
    maxOrder: string;
    minOrder: string;
    reOrderlevel: string;
    cpu: number;
    rPU: number;
    qty:number;
    Quantity:number;
    categoryName:string;
    subcategoryName:string;
  supplyName: string;
  openingStock: string;
  url: string;
  pstock:number;
   boxQuantity:string;
   boxSize:any;
   consumeUOMId:number;
   conversionRate:number;
   branchIdOpening: string;
   purchaseUOMId: string;
}